### PR TITLE
Implementation of a Revised Look

### PR DESCRIPTION
**Pull request by Liongold**
I've made some changes to the HTML templates to aid the CSS implementation, to fix a missing class in the top bar (a missing =) and removed an unclosed element that resulted in an extra column in some tables. 

I've also did a small change of headers in the README. 

Just for information, are these changes pushed to the actual site immediately or is there a test site for this?

### CODE REVIEW

**Review by mmohrhard — APPROVED** [review]

**Comment by mmohrhard** [comment]
This seems to still contain some issues. In the header bar you can see some position issues with the elements. It will take me some days to find some time to look into the css issues.

**Comment by Liongold** [comment]
I'll have a look at the conflict and the issues..

**Comment by mmohrhard** [comment]
I fixed the conflict already. The only problem is the rendering.

**Comment by Liongold** [comment]
On this side, it's reporting there's still a merge conflict. Anyway, I fixed two issues with the code I proposed. Do these fix the rendering problem you have?

**Comment by mmohrhard** [comment]
This has just been merged to master with a number of small fixes. Thanks a lot for your work.

**Comment by mmohrhard** [comment]
And now also deployed to the production instance. Thanks a lot for your work.

**Comment by Liongold** [comment]
I have tested the production and when the resolution gets smaller, the padding forces the top bar to be divided in two lines. 

To fix this, I thought of two ways either

* remove the left-pad and right-pad classes and add `text-align: center` to the width_33 class

or 

* add `box-sizing: border-box` to the width_33 class. 

Should I open a pull request or you can do it yourself? On my end, I think both have the same effect but I'd prefer the text-align approach.

**Comment by mmohrhard** [comment]
Opening a new pull request would be greatly appreciated.

**Comment by Liongold** [comment]
I have thought a little bit more on this and opted for a completely different approach. I've opened a pull request for it in #44.

**Pull request closed without merging**
